<?php

namespace JobBundle\Repository;

/**
 * JobCatagoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
