<?php

namespace JobBundle\Repository;

/**
 * JobSeekerResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSeekerResumeRepository extends \Doctrine\ORM\EntityRepository
{
}
