<?php

namespace JobBundle\Repository;

/**
 * JobSubCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSubCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
