<?php

namespace JobBundle\Repository;

/**
 * resumeEducationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class resumeEducationRepository extends \Doctrine\ORM\EntityRepository
{
}
