<?php

namespace JobBundle\Repository;

/**
 * workExpResumeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class workExpResumeRepository extends \Doctrine\ORM\EntityRepository
{
}
